ProModel/Controllers/ContactChildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using WebExplorer.Models;

namespace WebExplorer.Controllers
{
    public class ContactChildController : RenderMvcController
    {

        [HttpGet]
        public ActionResult ContactChild(ContactChildModel contactChild)
        {

            return CurrentTemplate(contactChild);
        }
    }
}

ProModel/Controllers/FooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Web.Mvc;
using System.Web.Mvc;

namespace WebExplorer.Controllers
{
    public class FooterController : SurfaceController
    {
        public ActionResult RenderFooter()
        {

            return PartialView("~/Views/Partials/WebBase/Footer.cshtml");
        }
    }
}

ProModel/Controllers/ForgotPasswordController.cs
using WebExplorer.Models;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;

namespace WebExplorer.Controllers
{
    public class ForgotPasswordController : SurfaceController
    {
        public ActionResult ForgotPassword(ForgotPasswordModel forgotPasswordModel)
        {
            var member = Services.MemberService.GetByEmail(forgotPasswordModel.Email);

            if (member != null)
            {
                string email = member.Email;
                if (!string.IsNullOrEmpty(email))
                {
                    string passwd = Membership.GeneratePassword(8, 0);
                    Services.MemberService.SavePassword(member, passwd);

                    SmtpClient client = new SmtpClient();
                    var message = new MailMessage("teste1@teste.com", email)
                    {
                        Subject = "New Password",
                        Body = "Your new password is: " + passwd
                    };
                    client.Send(message);
                }
            }

            return PartialView();
        }
    }
}

ProModel/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Web.Mvc;
using System.Web.Mvc;

namespace WebExplorer.Controllers
{
    public class HeaderController : SurfaceController
    {
        public ActionResult RenderHeader()
        {

            return PartialView("~/Views/Partials/WebBase/Header.cshtml");
        }
    }
}

ProModel/Controllers/LogoutController.cs
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using WebExplorer.Models;

namespace WebExplorer.Controllers
{
    public class LogoutController : SurfaceController
    {


        public ActionResult RenderLogout()
        {
            return PartialView("_Logout", null);
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }
    }
}

ProModel/Controllers/MemberController.cs
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using WebExplorer.Models;

namespace WebExplorer.Controllers
{
    public class MemberController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    UrlHelper myHelper = new UrlHelper(HttpContext.Request.RequestContext);
                   
                   return Redirect("/home/");
                }
                else
                {
                    ModelState.AddModelError("", "Datos incorretos.");
                    
                }
                
            }
            return CurrentUmbracoPage();
        }
        
    }
}

        

ProModel/Controllers/PersonGalleryController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedModels;
using WebExplorer.Models;

namespace WebExplorer.Controllers
{
    public class PersonGalleryController : RenderMvcController
    {
        [HttpGet]
        public ActionResult PersonGallery(ContentModel content)
        {
            var umbUsers = new List<UserModel>();
            var allUsers = Services.MemberService.GetAllMembers();
            var persons = new PersonGalleryModel(content.Content);
            foreach (var item in allUsers)
            {


                var Nome = item.GetValue<string>("nome");

                var avatarId = item.GetValue<int>("avatar");

                var avatar = UmbracoContext.MediaCache.GetById(avatarId);

                var umbUser = new UserModel();

                umbUser.Nome = Nome;
                umbUser.Avatar = avatar;
                umbUser.ImagemUrl = avatar?.Url;



                umbUsers.Add(umbUser);


            }
            persons.UmbUsers = umbUsers;

            return CurrentTemplate(persons);

        }
    }
}

ProModel/Controllers/RegisterController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using WebExplorer.Models;

namespace WebExplorer.Controllers
{
    public class RegisterController : SurfaceController
    {
        [HttpGet]
        public ActionResult RenderRegister(string hello)
        {
            ViewBag.hello = hello;
            return PartialView();
        }

        [HttpPost]

        public ActionResult RenderRegister(RegisterModel model)
        {
            var memberService = Services.MemberService;

            if (ModelState.IsValid)
            {
                var newuser = Membership.CreateUser(model.Username, model.Password, model.Email);
                Services.MemberService.AssignRole(newuser.UserName, "Registrados");
                return PartialView();

            }
            else
            {
                return View("~/home/");
            }

        }
    }
}

ProModel/Views/Base.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Base>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}

ProModel/Views/ContactChild.cshtml
@using WebExplorer.Controllers
@using WebExplorer.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "WebBase.cshtml";
}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Explorer</title>
        <meta name="description" content="Explorer Website.">
        <meta name="keywords" content="The Explorer website.">

        <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

        <link href="~/css/styles-merged.css" rel="stylesheet" />

        <link href="~/css/style.min.css" rel="stylesheet" />

        <link href="~/css/custom.css" rel="stylesheet" />
        <script src="~/scripts/html5shiv.min.js"></script>
        <script src="~/scripts/vendor/respond.min.js"></script>
    </head>
</html>
    <section class="recent-posts">
        <div class="container">
            @*<iframe width="1000" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=&amp;aq=&amp;sll=37.422023,-122.084337&amp;sspn=0.00357,0.008229&amp;ie=UTF8&amp;ll=37.421981,-122.084531&amp;spn=0.001785,0.004115&amp;t=m&amp;z=18&amp;output=embed"></iframe>*@
            <div class="row">
                @using (Html.BeginUmbracoForm<ContactEntrySurfaceController>("ContactEntry", FormMethod.Post, "form-horizontal"))
                {
                    var contactEntryModel = (ContactEntryModel)ViewBag.contactEntryModel;

                    <div class="col-md-8">
                        @*<h3>@title</h3>*@
                        <hr>
                        @*<p>@entryText</p>*@
                        <br />
                        <p id="feedback"></p>


                        <form role="form" id="contact-form" name="contact-form" method="post" action="" class="contact-form">
                            <div class="form-group col-md-6">
                                <span class="orange">Primeiro nome:</span>
                                <label class="sr-only" for="exampleInputEmail1">Your Name: *</label>
                                @Html.TextBoxFor(m => contactEntryModel.NomeCompleto, new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-6">
                                <span class="orange">Segundo nome:</span>
                                <label class="sr-only" for="exampleInputEmail1">Email: *</label>
                                @Html.TextBoxFor(m => contactEntryModel.Email, new { @class = "form-control" })
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group">
                                <span class="orange">Orçamentoe:</span>
                                <label class="sr-only" for="exampleInputEmail1">Subject:</label>
                                @Html.TextBoxFor(m => contactEntryModel.Orcamento, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <span class="orange">Email:</span>
                                @Html.TextBoxFor(m => contactEntryModel.Requisitos, new { @class = "form-control" })
                            </div>
                            <input id="submit-button" type="submit" class="btn btn-lg btn-info" value="Submit">
                        </form>
                    </div>
                }
                <div class="col-md-4">
                    @*<h3>@rightTitle</h3>*@
                    <hr>
                    @*@rightText*@
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </section>

    <script type="text/javascript" src="js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript">
        function send_special_order() {
            var data1 = $('#name').val();
            var data2 = $('#subject').val();
            var data3 = $('#email').val();
            var data4 = $('#message').val();
            $.ajax({
                type: "POST",
                url: "send.php",
                dataType: "json",
                data: ({ "name": data1, "subject": data2, "email": data3, "message": data4 }),
                success: function () {
                },
                complete: function () {
                    $('#feedback').append('<p>Thank you for sending us a message. Our specialists will contact you as soon as possible.</p><p>Your message details are:</p>\n\
                                    <ul>\n\
                                        <li>Name: <b>' + data1 + '</b></li>\n\
                                        <li>Email: <b>' + data3 + '</b></li>\n\
                                        <li>Subject: <b>' + data2 + '</b></li>\n\
                                        <li>Message: <b>' + data4 + '</b></li>\n\
                                    </ul>\n\
                                    <p>If you want to change your information press the button:\n\
                                    <p><a href="#" id="send-more" class="btn btn-lg btn-info">edit info</a></p>');
                    $('#contact-form').slideUp();
                    $('#send-more').click(function (e) {
                        e.preventDefault()
                        $('#contact-form').slideDown();
                        $('#feedback').html('');
                    });
                }
            });
        }
        $('#contact-form').submit(function () {
            send_special_order();
            return false;
        });
        </script>

        <script src="~/scripts/scripts.min.js"></script>

    <script src="~/scripts/main.min.js"></script>

    <script src="~/scripts/custom.js"></script>
   

ProModel/Views/ContactEntries.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}

ProModel/Views/ContactsEntries.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ContactsEntries>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = null;
}

ProModel/Views/Galeria.cshtml
@using WebExplorer.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<PersonGalleryModel>
@{
    Layout = "WebBase.cshtml";

}


<section id="work" data-stellar-background-ratio="0.5">
    <div>
        <div class="container">
            <div class="row">

                <div class="col-md-12 col-sm-12">
                    <div class="section-title">
                        <br />
                        <br />
                        <h2><font color="#003000">Nossa Galeria</font></h2>
                    </div>
                </div>
                <br />
                <br />
                @foreach (var umbUser in Model.UmbUsers)
                {
                    <img src="@(umbUser.Avatar.Url)" class="img-responsive" alt="Work">

                    <div class="work-info">
                        <h3>@umbUser.Nome</h3>
                    </div>
                
            
        
            }


        </div>
    </div>
</section>

ProModel/Views/Lingua.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Lingua>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = null;
}

ProModel/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "WebBase.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Explorer</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Login/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login/css/main.css">
    <!--===============================================================================================-->
</head>
@*
    <body>

        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                    <form class="login100-form validate-form flex-sb flex-w">
                        <span class="login100-form-title p-b-32">
                            Account Login
                        </span>

                        <span class="txt1 p-b-11">
                            Username
                        </span>
                        <div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
                            <input class="input100" type="text" name="username">
                            <span class="focus-input100"></span>
                        </div>

                        <span class="txt1 p-b-11">
                            Password
                        </span>
                        <div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
                            <span class="btn-show-pass">
                                <i class="fa fa-eye"></i>
                            </span>
                            <input class="input100" type="password" name="pass">
                            <span class="focus-input100"></span>
                        </div>

                        <div class="flex-sb-m w-full p-b-48">
                                <div class="contact100-form-checkbox">
                                    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                                    <label class="label-checkbox100" for="ckb1">
                                        Remember me
                                    </label>
                                </div>

                                <div>
                                    <a href="#" class="txt3">
                                        Forgot Password?
                                    </a>
                                </div>
                            </div>

                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn" type="submit" name="login">
                                Login
                            </button>
                        </div>

                        &nbsp;


                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn" onclick="location.href='/Register/'" type="button" name="register">
                                Register
                            </button>
                        </div>


                    </form>
                </div>
            </div>
        </div>


        <div id="dropDownSelect1"></div>*@

<!--===============================================================================================-->
<script src="~/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/bootstrap/js/popper.js"></script>
<script src="~/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/daterangepicker/moment.min.js"></script>
<script src="~/Login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/Login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/Login/js/main.js"></script>

    </body>
</html>


@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "WebBase.cshtml";
}
@{ Html.RenderAction("RenderLogin", "Member");}

ProModel/Views/PersonGallery.cshtml
@using WebExplorer.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<PersonGalleryModel>
@{
    Layout = "WebBase.cshtml";

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Explorer</title>
    <meta name="description" content="Explorer Website.">
    <meta name="keywords" content="The Explorer website.">

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="~/css/styles-merged.css" rel="stylesheet" />

    <link href="~/css/style.min.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
    <script src="~/scripts/html5shiv.min.js"></script>
    <script src="~/scripts/vendor/respond.min.js"></script>
</head>

<section id="work" data-stellar-background-ratio="0.5">
    <div>
        <div class="container">
            <div class="row">

                <div class="col-md-12 col-sm-12">
                    <div class="section-title">
                        <br />
                        <br />
                        <h2><font color="#003000">Nossa Galeria</font></h2>
                    </div>
                </div>
                <br />
                <br />
                @foreach (var umbUser in Model.UmbUsers)
                {
                    <img src="@(umbUser.ImagemUrl)" class="img-responsive" alt="Work">

                    <div class="work-info">
                        <h3>@umbUser.Nome</h3>
                    </div>



                }
            </div>

        </div>
    </div>
</section>
<script src="~/scripts/scripts.min.js"></script>

<script src="~/scripts/main.min.js"></script>

<script src="~/scripts/custom.js"></script>

ProModel/Views/View.cshtml
@using System.Web.Mvc.Html
@using Umbraco.Web
@using WebExplorer.Controllers
@using WebExplorer.Models
@model Umbraco.Web.Models.ContentModel

@{
    Layout = "WebBase.cshtml";



}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Explorer</title>
    <meta name="description" content="Explorer Website.">
    <meta name="keywords" content="The Explorer website.">

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="~/css/styles-merged.css" rel="stylesheet" />

    <link href="~/css/style.min.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
    <script src="~/scripts/html5shiv.min.js"></script>
    <script src="~/scripts/vendor/respond.min.js"></script>
</head>

<div>
    <div class="container" style="padding-top: 60px;">
        <h1 class="page-header">Profile Information</h1>
        <div class="tab-pane active" id="username">
            <h3>Avatar</h3>

        </div>

ProModel/Views/_Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<WebExplorer.Models.LoginModel>
@using Umbraco.Web
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Explorer</title>
    <meta name="description" content="Explorer Website.">
    <meta name="keywords" content="The Explorer website.">

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="~/css/styles-merged.css" rel="stylesheet" />

    <link href="~/css/style.min.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
    <script src="~/scripts/html5shiv.min.js"></script>
    <script src="~/scripts/vendor/respond.min.js"></script>
</head>
@if (!Umbraco.MemberIsLoggedOn())
{
    using (Html.BeginUmbracoForm("SubmitLogin", "Member", System.Web.Mvc.FormMethod.Post, new { id = "login" }))
    {
        <body>

            <div class="limiter">
                <div class="container-login100">
                    <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                        <form class="login100-form validate-form flex-sb flex-w">
                            <span class="login100-form-title p-b-32">
                                Account Login
                            </span>

                            <span class="txt1 p-b-11">
                                @Html.AntiForgeryToken()
                                @Html.LabelFor(m => m.Username)
                                @Html.TextBoxFor(m => m.Username, new { placeholder = "Username" })
                            </span>


                            <span class="txt1 p-b-11">
                                @Html.LabelFor(m => m.Password)
                                @Html.PasswordFor(m => m.Password, new { placeholder = "Password" })
                            </span>
                            @Html.ValidationSummary()

                            <span class="focus-input100"></span>
                            <div>
                                <a href="/forgotpass/" class="txt3">
                                    Forgot Password?
                                    &nbsp;

                                </a>

                            </div>
                            &nbsp;
                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" type="submit" name="login">
                                    Login
                                </button>
                            </div>

                            &nbsp;
                            <a href="~/register/">
                                <button class="login100-form-btn" type="button" name="register" style="margin:inherit;">
                                    Register
                                </button>
                            </a>


                        </form>
                    </div>


                </div>

            </div>


        </body>
    }
}
else
{
    Html.RenderAction("RenderLogout", "Logout");
}
<script src="~/scripts/scripts.min.js"></script>

<script src="~/scripts/main.min.js"></script>

<script src="~/scripts/custom.js"></script>

ProModel/Views/_Logout.cshtml
@*@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@if (Umbraco.MemberIsLoggedOn())
{
    using (Html.BeginUmbracoForm("SubmitLogout", "Logout", System.Web.Mvc.FormMethod.Post, new { id = "logout" }))
    {
        @Html.AntiForgeryToken()
        var myUser = System.Web.Security.Membership.GetUser();
        if (myUser != null)
        {
            <p><i>Logged in as</i> <span>@myUser.UserName</span></p>
            <button name="logout" type="submit"><span>logout</span> <i class="fa fa-arrow-right"></i></button>


        }
    }
}*@

ProModel/Views/about.cshtml
@model Umbraco.Web.Models.ContentModel

@{
    Layout = "WebBase.cshtml";

    var title = Model.Content.Value<string>("title");
    var subTitle = Model.Content.Value<string>("subTitle");
    var photo1 = Model.Content.Value<IPublishedContent>("photo1");

}
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Explorer</title>
    <meta name="description" content="Explorer Website.">
    <meta name="keywords" content="The Explorer website.">

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="~/css/styles-merged.css" rel="stylesheet" />

    <link href="~/css/style.min.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />
    <script src="~/scripts/html5shiv.min.js"></script>
    <script src="~/scripts/vendor/respond.min.js"></script>
</head>
@* the fun starts here *@
<html>
<body>
    <!-- START: header -->
    <!-- END: header -->
    <section class="probootstrap-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <p><img src="@photo1.Url" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-7 col-md-push-5">
                    <h2>@title</h2>








                    <p>@subTitle</p>
                </div>
            </div>
        </div>
    </section>
    <!-- END section -->

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
    </div>
    <script src="~/scripts/scripts.min.js"></script>

    <script src="~/scripts/main.min.js"></script>

    <script src="~/scripts/custom.js"></script>
</body>
</html>

ProModel/Views/webBase.cshtml
@using System.Web.Mvc.Html
@inherits Umbraco.Web.Mvc.UmbracoViewPage


@{
    ViewBag.Title = "WebBase";
}

@* the fun starts here *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Explorer</title>
    <meta name="description" content="Explorer Website.">
    <meta name="keywords" content="The Explorer website.">

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="~/css/styles-merged.css" rel="stylesheet" />

    <link href="~/css/style.min.css" rel="stylesheet" />

    <link href="~/css/custom.css" rel="stylesheet" />

    <script src="~/scripts/html5shiv.min.js"></script>
    <script src="~/scripts/vendor/respond.min.js"></script>

</head>
<body>
    <!-- START: header -->
    @{Html.RenderAction("RenderHeader", "Header");}

    @RenderBody()
    <!-- END: header -->


    @{Html.RenderAction("RenderFooter", "Footer");}


    <script src="~/scripts/scripts.min.js"></script>

    <script src="~/scripts/main.min.js"></script>

    <script src="~/scripts/custom.js"></script>
</body>
</html>